info:
  app:
    name: catalog-metadata-service
    description: Catalog Metadata rest

server:
  port: 0

catalogmetadata:
    cassandra:
        keyspace: localtestcluster
        port: 9043
        host: localhost

zipkin:
    collector-hostname: localhost
