info:
  app:
    name: catalog-catalogmetadata-rest
    description: Catalog Metadata rest

server:
  port: 8080

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

catalogmetadata:
    cassandra:
        keyspace: jimntestlocal
        port: 9042
        host: localhost

---
spring:
    profiles: docker

catalogmetadata:
    cassandra:
        keyspace: jimntestlocal
        port: 9042
        host: cassandra