info:
  app:
    name: catalog-metadata-service
    description: Catalog Metadata rest

server:
  port: 9083

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

catalogmetadata:
    cassandra:
        keyspace: localtestcluster
        port: 9042
        host: localhost
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: docker

catalogmetadata:
    cassandra:
        keyspace: localtestcluster
        port: 9042
        host: cassandra

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/