info:
  app:
    name: catalog-metadata-service
    description: Catalog Metadata rest

server:
  port: 0

zipkin:
    collector-hostname: localhost

---
spring:
  profiles: local

server:
  port: 9083