info:
  app:
    name: catalog-metadata-service
    description: Catalog Metadata rest

server:
  port: 8080

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

catalogmetadata:
    cassandra:
        keyspace: jimntestlocal
        port: 9042
        host: localhost

---
spring:
    profiles: docker

catalogmetadata:
    cassandra:
        keyspace: jimntestlocal
        port: 9042
        host: cassandra

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/